general {
    lock_cmd = omarchy-lock-screen
    before_sleep_cmd = loginctl lock-session
    inhibit_sleep = 3
}

listener {
    timeout = 150
    on-timeout = pidof hyprlock || omarchy-launch-screensaver
}

listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

listener {
    timeout = 330
    on-timeout = brightnessctl -sd '*::kbd_backlight' set 0
}

listener {
    timeout = 330
    on-timeout = hyprctl dispatch dpms off
}

idle {
    ignore_activity = network
}

